title: "AbsolutSin-ema"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "se-edu/absolutsinema-level3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
